name: Build and Push Container
on: [push]
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup HashiCorp packer
        uses: hashicorp/setup-packer@v2.0.0
        
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Run `packer init`
        id: init
        run: "packer init ./docker-ubuntu-pwsh.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer -var tag=${GITHUB_RUN_ID} -var docker_repo=${DOCKER_REPO} -var docker_username=${DOCKER_USERNAME} -var docker_password=${DOCKER_PASSWORD} validate ./docker-ubuntu-pwsh.pkr.hcl"
        
      - name: Run `packer build`
        id: build
        run: "packer -var tag=${GITHUB_RUN_ID} -var docker_repo=${DOCKER_REPO} -var docker_username=${DOCKER_USERNAME} -var docker_password=${DOCKER_PASSWORD} build ./docker-ubuntu-pwsh.pkr.hcl"
