name: Build and Push Container
on: [push]
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup HashiCorp packer
        uses: hashicorp/setup-packer@v2.0.0
        
      - name: Check out the repo
        uses: actions/checkout@v3
