name: Setup Packer
on: [push]
jobs:
  setup-packer:
    runs-on: ubuntu-latest

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v2.0.0

jobs:
  checkout-repo:
  needs: setup-packer
        
      - name: Check out the repo
        uses: actions/checkout@v3
