name: Build and Push Container
on: [push]
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup HashiCorp packer
        uses: hashicorp/setup-packer@v2.0.0
        
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Run `packer init`
        id: init
        run: "packer init ./docker-ubuntu-pwsh.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate -var tag=${{ env.GITHUB_RUN_ID }} -var docker_repo=${{ vars.DOCKER_REPO }} -var docker_username=${{ vars.DOCKER_USERNAME }} -var docker_password=${{ secrets.DOCKER_PASSWORD }} ./docker-ubuntu-pwsh.pkr.hcl"
        
      - name: Run `packer build`
        id: build
        run: "packer build -var tag=${{ env.GITHUB_RUN_ID }} -var docker_repo=${{ vars.DOCKER_REPO }} -var docker_username=${{ vars.DOCKER_USERNAME }} -var docker_password=${{ secrets.DOCKER_PASSWORD }} ./docker-ubuntu-pwsh.pkr.hcl"
